#!/usr/bin/env bash
# Relink BallpadStrikers against a modified FFmpeg.
#
# This is the relinking half of the material set that
# scripts/native/ffmpeg-relink-offer.sh packages for the statically linked
# FFmpeg the shipped app carries. LGPL-2.1-or-later section 6 only lets a work
# link this library statically if the recipient can also modify the library and
# relink; this script is what makes that possible, because it re-runs the exact
# link command the shipped build used with libavcodec.a and libavutil.a replaced
# by whatever the caller supplies.
#
# The command it re-runs is not reconstructed by hand: the offer directory holds
# the line ninja itself printed for the app target, so the packaged set tracks
# the shipped link instead of a remembered one.
#
# Use: scripts/native/lib/ffmpeg-relink.sh --offer-dir DIR [--avcodec PATH]
#                                          [--avutil PATH] [--out PATH]
#
#   --offer-dir DIR   the directory scripts/native/ffmpeg-relink-offer.sh wrote
#   --avcodec PATH    a libavcodec.a to link instead of the pinned one
#   --avutil PATH     a libavutil.a to link instead of the pinned one
#   --out PATH        where the relinked executable goes. Defaults inside the
#                     offer directory; the shipped executable is never a target
#
# With no --avcodec/--avutil this relinks the pinned archives, which is the
# check that the packaged set still relinks at all.

set -euo pipefail

OFFER_DIR=""
AVCODEC=""
AVUTIL=""
OUT=""

die() { printf 'ERROR %s\n' "$*" >&2; exit 1; }

usage() {
    sed -n '17,29p' "$0"
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --offer-dir) [ "$#" -ge 2 ] || die "missing value for $1"; OFFER_DIR="$2"; shift 2 ;;
        --avcodec)   [ "$#" -ge 2 ] || die "missing value for $1"; AVCODEC="$2"; shift 2 ;;
        --avutil)    [ "$#" -ge 2 ] || die "missing value for $1"; AVUTIL="$2"; shift 2 ;;
        --out)       [ "$#" -ge 2 ] || die "missing value for $1"; OUT="$2"; shift 2 ;;
        -h|--help)   usage; exit 0 ;;
        *) die "unknown argument: $1" ;;
    esac
done

[ -n "$OFFER_DIR" ] || die "--offer-dir is required"
[ -d "$OFFER_DIR" ] || die "no offer directory at $OFFER_DIR"
[ -f "$OFFER_DIR/offer.env" ] || die "$OFFER_DIR has no offer.env"
[ -f "$OFFER_DIR/LINK-COMMAND.txt" ] || die "$OFFER_DIR has no LINK-COMMAND.txt"

# offer.env is generated by the packaging script next to this one; the four names
# below are what it defines. Pre-seeding them keeps a damaged file a readable
# error under set -u instead of a bare unbound-variable exit.
BUILD_DIR=""
TARGET_BIN=""
PINNED_AVCODEC=""
PINNED_AVUTIL=""
# shellcheck source=/dev/null
. "$OFFER_DIR/offer.env"

[ -n "$BUILD_DIR" ] || die "offer.env does not define BUILD_DIR"
[ -n "$TARGET_BIN" ] || die "offer.env does not define TARGET_BIN"
[ -n "$PINNED_AVCODEC" ] || die "offer.env does not define PINNED_AVCODEC"
[ -n "$PINNED_AVUTIL" ] || die "offer.env does not define PINNED_AVUTIL"
[ -d "$BUILD_DIR" ] || die "the offer names a build directory that is gone: $BUILD_DIR"

[ -n "$AVCODEC" ] || AVCODEC="$PINNED_AVCODEC"
[ -n "$AVUTIL" ] || AVUTIL="$PINNED_AVUTIL"
[ -n "$OUT" ] || OUT="$OFFER_DIR/relinked/$(basename "$TARGET_BIN")"

# Absolute paths only: the link command runs in the build directory, so a
# caller's relative archive path would otherwise be resolved from somewhere else.
case "$AVCODEC" in /*) ;; *) AVCODEC="$(cd "$(dirname "$AVCODEC")" && pwd)/$(basename "$AVCODEC")" ;; esac
case "$AVUTIL" in /*) ;; *) AVUTIL="$(cd "$(dirname "$AVUTIL")" && pwd)/$(basename "$AVUTIL")" ;; esac

[ -f "$AVCODEC" ] || die "no libavcodec.a at $AVCODEC"
[ -f "$AVUTIL" ] || die "no libavutil.a at $AVUTIL"

SHIPPED="$BUILD_DIR/$TARGET_BIN"
[ -n "$OUT" ] || die "empty --out"
case "$OUT" in /*) ;; *) OUT="$(pwd)/$OUT" ;; esac
case "$OUT" in *"'"*) die "the --out path contains a single quote, which the substitution cannot carry: $OUT" ;; esac
[ "$OUT" != "$SHIPPED" ] || die "refusing to write the relinked executable over the shipped one at $SHIPPED; pass --out"
for path in "$AVCODEC" "$AVUTIL"; do
    case "$path" in
        *"'"*|*"&"*|*"|"*|*"\\"*) die "this path contains a character the substitution cannot carry: $path" ;;
    esac
done

mkdir -p "$(dirname "$OUT")"

command_line="$(cat "$OFFER_DIR/LINK-COMMAND.txt")"
relinked="$(
    printf '%s' "$command_line" \
        | sed -e "s|$PINNED_AVCODEC|$AVCODEC|g" \
              -e "s|$PINNED_AVUTIL|$AVUTIL|g" \
              -e "s|-o $TARGET_BIN|-o $OUT|g"
)"

# A substitution that changed nothing means the packaged command does not name
# what this script thinks it names -- a different build, or an offer assembled
# for another platform. Refuse rather than link something unintended.
[ "$relinked" != "$command_line" ] || die "the packaged link command never names $PINNED_AVCODEC or $TARGET_BIN; refusing to relink"
case "$relinked" in
    *"$AVCODEC"*) ;;
    *) die "the substituted command does not link $AVCODEC; refusing to relink" ;;
esac
case "$relinked" in
    *"-o $OUT"*) ;;
    *) die "the substituted command does not write $OUT; refusing to relink" ;;
esac

printf '==> relinking %s\n' "$OUT"
printf '    libavcodec %s\n' "$AVCODEC"
printf '    libavutil  %s\n' "$AVUTIL"
(
    cd "$BUILD_DIR"
    bash -c "$relinked"
)

[ -f "$OUT" ] || die "the link command reported success but produced no $OUT"
printf '==> relinked executable: %s bytes\n' "$(wc -c < "$OUT" | tr -d ' ')"
printf '    sha256 %s\n' "$(shasum -a 256 "$OUT" | awk '{print $1}')"
